from __future__ import annotations

from collections.abc import Generator

from fastapi import APIRouter, Depends, status
from sqlmodel import Session

from backend.core.database import engine
from backend.core.dependencies import get_current_user, require_role
from backend.core.exceptions import AppException
from backend.core.uow import UnitOfWork
from backend.pagos import service as pago_service
from backend.pagos.repository import PagoRepository
from backend.pagos.schemas import CrearPagoRequest, PagoResponse
from backend.pedidos.repository import PedidoRepository
from backend.usuarios.model import Usuario

router = APIRouter()


# ------------------------------------------------------------------
# Local UoW factory — registers pagos and pedidos repositories
# ------------------------------------------------------------------


def _get_uow() -> Generator[UnitOfWork, None, None]:
    """Per-request UnitOfWork for the pagos module."""
    from fastapi import HTTPException

    def _session_factory() -> Session:
        return Session(engine)

    uow = UnitOfWork(_session_factory)
    uow.__enter__()
    uow.repos.register("pagos", lambda s: PagoRepository(s))
    uow.repos.register("pedidos", lambda s: PedidoRepository(s))
    try:
        yield uow
    except (HTTPException, AppException):
        uow.session.commit()
        raise
    except Exception:
        uow.session.rollback()
        raise
    finally:
        uow.session.close()


# ------------------------------------------------------------------
# Endpoints
# ------------------------------------------------------------------


@router.post(
    "/crear",
    response_model=PagoResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create a payment via MercadoPago",
)
def crear_pago(
    body: CrearPagoRequest,
    uow: UnitOfWork = Depends(_get_uow),
    current_user: Usuario = Depends(require_role("CLIENT", "ADMIN")),
) -> PagoResponse:
    """Create a payment in MercadoPago and register it in the database.

    Receives a card token generated by the MercadoPago SDK on the
    frontend, creates the payment via the MercadoPago API with an
    idempotency key, and persists the result atomically via UoW.
    """
    pago = pago_service.crear_pago(uow, body, current_user)
    uow.commit()
    return PagoResponse.model_validate(pago)
