"""alter_direccionentrega_granular_fields_and_soft_delete

Revision ID: 0593195db4b0
Revises: 0003_add_cantidad_unidad
Create Date: 2026-05-13 14:30:17.291674

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0593195db4b0'
down_revision = '0003_add_cantidad_unidad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direccionentrega', sa.Column('calle', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('direccionentrega', sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('direccionentrega', sa.Column('piso', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('direccionentrega', sa.Column('departamento', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('direccionentrega', sa.Column('provincia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('direccionentrega', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('direccionentrega', 'codigo_postal',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.alter_column('direccionentrega', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('direccionentrega', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('direccionentrega', 'linea1')
    op.drop_column('direccionentrega', 'linea2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direccionentrega', sa.Column('linea2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('direccionentrega', sa.Column('linea1', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('direccionentrega', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('direccionentrega', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('direccionentrega', 'codigo_postal',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('direccionentrega', 'deleted_at')
    op.drop_column('direccionentrega', 'provincia')
    op.drop_column('direccionentrega', 'departamento')
    op.drop_column('direccionentrega', 'piso')
    op.drop_column('direccionentrega', 'numero')
    op.drop_column('direccionentrega', 'calle')
    # ### end Alembic commands ###
