"""make_forma_pago_nullable_pedido

Revision ID: f9f9bdb45616
Revises: 0593195db4b0
Create Date: 2026-05-13 18:24:44.640917

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f9bdb45616'
down_revision = '0593195db4b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido', 'forma_pago_codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # Add CHECK constraint to ensure stock_cantidad never goes negative
    op.create_check_constraint(
        'ck_producto_stock_cantidad_non_negative',
        'producto',
        'stock_cantidad >= 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_producto_stock_cantidad_non_negative',
        'producto',
        type_='check',
    )
    op.alter_column('pedido', 'forma_pago_codigo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
